# Generated by Django 4.0.5 on 2022-06-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_food_image_alter_food_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='image',
            new_name='imgSrc',
        ),
        migrations.AddField(
            model_name='food',
            name='imgAlt',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
