# Generated by Django 4.0.5 on 2022-06-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_rename_image_food_imgsrc_food_imgalt'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
